### PR TITLE
Run tests also on Python 3.8

### PR DESCRIPTION
**Pull request by pombredanne**
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
Not sure why such a tiny change brought so much CI failure

**Comment by altendky** [comment]
And now the build has been cleaned up...  `:|`  Closing to reopen and trigger CI.

**Comment by altendky** [comment]
Kick CI

**Comment by altendky** [comment]
It kind of seems like the personal access token for the CI isn't working.  Though I think I replaced it before and just did again.  So I'll have to keep digging down I guess.

**Comment by altendky** [comment]
Despite not having expired it seems that just regenerating didn't cut it.  I had to delete the PAT used for CI and create a new one.

**Comment by altendky** [comment]
Thanks.  I'll go add 3.9 now too.

**Comment by pombredanne** [comment]
@altendky Thank you ++ ... at this stage I am integrating romp (and may be boots TBD) to support building all the thirdparty wheels for scancode and all our projects.
Then all the wheels are stored on a publicly accessible and privately managed PyPI "simple" repo, e.g. exactly and no more and no less than a bunch of attachments to a Github release at https://github.com/nexB/thirdparty-packages/releases/pypi that can be used with a `pip --find-links --no-index`
(Not sure if you knew of the trick and it can come handy as this requires no setup at all )

**Pull request merged**
